import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import Link from "next/link";
import { requirePlatformOwner } from "../../lib/auth";
import { fetchSecureActorBackendJson, writeSecureActorBackendJson } from "../../lib/server-api";

export const dynamic = "force-dynamic";
type Binding = { id: string; requestType: string; subject: string; verifiedEmail?: string | null; status: string; candidateAppUserId?: string | null; rowVersion: number; expiresAt: string };
type Identity = { id: string; subject: string; status: string; rowVersion: number; appUser: { id: string; email: string; displayName?: string | null; active: boolean } };
type Event = { id: string; eventType: string; previousStatus?: string | null; nextStatus?: string | null; reasonCode?: string | null; createdAt: string };
type Candidate = { id: string; email: string; displayName?: string | null; active: boolean };

function text(form: FormData, key: string) { const value = form.get(key); return typeof value === "string" ? value.trim() : ""; }
function mutationHeaders(form: FormData) { return { "If-Match": `"${text(form, "rowVersion")}"`, "Idempotency-Key": text(form, "idempotencyKey") }; }
async function mutateRequest(form: FormData) { "use server"; await requirePlatformOwner(); const id = text(form,"id"); const action=text(form,"action"); const payload: Record<string,string>={reason:text(form,"reason")}; if(action==="select-candidate")payload.candidateAppUserId=text(form,"candidateAppUserId"); if(action==="create-candidate-user"){payload.email=text(form,"email");payload.displayName=text(form,"displayName");} await writeSecureActorBackendJson(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identity-binding-requests/${encodeURIComponent(id)}/${action}`,"POST",payload,mutationHeaders(form)); revalidatePath("/external-identities"); }
async function mutateIdentity(form: FormData) { "use server"; await requirePlatformOwner(); const id=text(form,"id"); const action=text(form,"action"); await writeSecureActorBackendJson(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identities/${encodeURIComponent(id)}/${action}`,"POST",{reason:text(form,"reason")},mutationHeaders(form)); revalidatePath("/external-identities"); }
async function createRequest(form: FormData) { "use server"; await requirePlatformOwner(); await fetchSecureActorBackendJson(process.env.PLATFORM_API_BASE_URL,"/api/v1/platform/external-identity-binding-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestType:"BIND",provider:"FIREBASE",subject:text(form,"subject"),verifiedEmail:text(form,"verifiedEmail")||null,emailVerified:text(form,"emailVerified")==="true",candidateAppUserId:text(form,"candidateAppUserId")||null,targetExternalIdentityId:null,reason:text(form,"reason")})}); revalidatePath("/external-identities"); }

function MutationFields({ id, version, action }: { id: string; version: number; action: string }) { return <><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value={action}/><input type="hidden" name="rowVersion" value={version}/><input type="hidden" name="idempotencyKey" value={`platform-admin:${randomUUID()}`}/></>; }
function EventList({items}:{items:Event[]}) { return <div className="mt-5"><h3 className="font-black">Audit events</h3><ol className="mt-2 grid gap-1 text-sm">{items.map(item=><li key={item.id} className="rounded bg-kv-bg p-2">{new Date(item.createdAt).toISOString()} · {item.eventType} · {item.previousStatus??"—"} → {item.nextStatus??"—"} · {item.reasonCode??"—"}</li>)}</ol></div>; }

export default async function ExternalIdentitiesPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  await requirePlatformOwner(); const params=await searchParams; const requestId=params.request; const identityId=params.identity; const q=params.q??"";
  const [requests,identities,candidates]=await Promise.all([
    fetchSecureActorBackendJson<{items:Binding[]}>(process.env.PLATFORM_API_BASE_URL,"/api/v1/platform/external-identity-binding-requests?limit=100"),
    fetchSecureActorBackendJson<{items:Identity[]}>(process.env.PLATFORM_API_BASE_URL,"/api/v1/platform/external-identities?limit=100"),
    fetchSecureActorBackendJson<{items:Candidate[]}>(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identity-candidates?q=${encodeURIComponent(q)}`),
  ]);
  const selectedRequest=requestId?await fetchSecureActorBackendJson<Binding>(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identity-binding-requests/${encodeURIComponent(requestId)}`):null;
  const requestEvents=requestId?await fetchSecureActorBackendJson<{items:Event[]}>(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identity-binding-requests/${encodeURIComponent(requestId)}/events`):null;
  const selectedIdentity=identityId?await fetchSecureActorBackendJson<Identity>(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identities/${encodeURIComponent(identityId)}`):null;
  const identityEvents=identityId?await fetchSecureActorBackendJson<{items:Event[]}>(process.env.PLATFORM_API_BASE_URL,`/api/v1/platform/external-identities/${encodeURIComponent(identityId)}/events`):null;
  return <main className="min-h-screen bg-kv-bg p-6 text-kv-ink"><div className="mx-auto max-w-[1280px]">
    <div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-[.18em] text-kv-red">Security control plane</div><h1 className="mt-2 text-3xl font-black text-kv-navy">Firebase UID bindings</h1></div><Link href="/" className="rounded-full border border-kv-line bg-white px-4 py-2 font-black">Назад</Link></div>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-md border border-kv-line bg-white p-4"><h2 className="font-black">Новый BIND</h2><form action={createRequest} className="mt-3 grid gap-2"><input name="subject" required placeholder="Firebase UID" className="rounded border p-2"/><input name="verifiedEmail" type="email" placeholder="Verified email" className="rounded border p-2"/><label><input type="checkbox" name="emailVerified" value="true"/> email_verified=true</label><select name="candidateAppUserId" className="rounded border p-2"><option value="">Кандидат не выбран</option>{candidates.items.map(x=><option key={x.id} value={x.id}>{x.email}</option>)}</select><textarea name="reason" required minLength={10} maxLength={1000} placeholder="Причина" className="rounded border p-2"/><button className="rounded-full bg-kv-navy px-4 py-2 font-black text-white">Создать</button></form></div>
    <div className="rounded-md border border-kv-line bg-white p-4"><h2 className="font-black">Поиск AppUser</h2><form method="get" className="mt-3 flex gap-2"><input name="q" defaultValue={q} className="min-w-0 flex-1 rounded border p-2"/><button className="rounded-full border px-4 font-black">Найти</button></form>{candidates.items.map(x=><div key={x.id} className="border-t py-2 text-sm">{x.email} · {x.displayName??"—"} · {x.active?"active":"inactive"}</div>)}</div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><List title="Binding requests">{requests.items.map(x=><Link key={x.id} href={`/external-identities?request=${x.id}`} className="rounded border p-3"><b>{x.requestType} · {x.status}</b><div className="break-all text-xs">{x.subject}</div><div className="text-xs">v{x.rowVersion} · {x.verifiedEmail??"no verified email"}</div></Link>)}</List><List title="Active / revoked identities">{identities.items.map(x=><Link key={x.id} href={`/external-identities?identity=${x.id}`} className="rounded border p-3"><b>{x.status} · {x.appUser.email}</b><div className="break-all text-xs">{x.subject}</div><div className="text-xs">v{x.rowVersion}</div></Link>)}</List></section>
    {selectedRequest?<section className="mt-6 rounded-md border border-kv-line bg-white p-4"><h2 className="font-black">Request {selectedRequest.id}</h2><p className="break-all text-sm">{selectedRequest.subject} · {selectedRequest.status} · v{selectedRequest.rowVersion}</p>{selectedRequest.status==="PENDING"?<div className="mt-4 grid gap-4 md:grid-cols-2"><form action={mutateRequest} className="grid gap-2"><MutationFields id={selectedRequest.id} version={selectedRequest.rowVersion} action="select-candidate"/><select name="candidateAppUserId" className="rounded border p-2">{candidates.items.map(x=><option key={x.id} value={x.id}>{x.email}</option>)}</select><Reason/><button className="rounded-full border p-2 font-black">Выбрать кандидата</button></form><form action={mutateRequest} className="grid gap-2"><MutationFields id={selectedRequest.id} version={selectedRequest.rowVersion} action="create-candidate-user"/><input name="displayName" required placeholder="Имя" className="rounded border p-2"/><input name="email" type="email" required defaultValue={selectedRequest.verifiedEmail??""} className="rounded border p-2"/><Reason/><button className="rounded-full border p-2 font-black">Создать AppUser</button></form>{["approve","reject","cancel"].map(action=><form action={mutateRequest} key={action} className="grid gap-2"><MutationFields id={selectedRequest.id} version={selectedRequest.rowVersion} action={action}/><Reason/><button className="rounded-full bg-kv-navy p-2 font-black text-white">{action}</button></form>)}</div>:null}<EventList items={requestEvents?.items??[]}/></section>:null}
    {selectedIdentity?<section className="mt-6 rounded-md border border-kv-line bg-white p-4"><h2 className="font-black">Identity {selectedIdentity.id}</h2><p className="break-all text-sm">{selectedIdentity.subject} · {selectedIdentity.status} · v{selectedIdentity.rowVersion}</p><form action={mutateIdentity} className="mt-4 grid max-w-xl gap-2"><MutationFields id={selectedIdentity.id} version={selectedIdentity.rowVersion} action={selectedIdentity.status==="ACTIVE"?"revoke":"reactivation-request"}/><Reason/><button className="rounded-full bg-kv-red p-2 font-black text-white">{selectedIdentity.status==="ACTIVE"?"Отозвать":"Запросить реактивацию"}</button></form><EventList items={identityEvents?.items??[]}/></section>:null}
  </div></main>;
}
function Reason(){return <textarea name="reason" required minLength={10} maxLength={1000} placeholder="Причина (10–1000)" className="rounded border p-2"/>;}
function List({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-md border border-kv-line bg-white p-4"><h2 className="font-black">{title}</h2><div className="mt-3 grid gap-2">{children}</div></div>;}
