import type { PartnerTenantConfig } from "../types";

export const aurumTenant: PartnerTenantConfig = {
  key: "aurum",
  name: "Aurum Key",
  legalLabel: "Realty NYC",
  city: "New York",
  country: "United States",
  domainLabel: "aurumkeynyc.com",
  accentLabel: "Manhattan / Brooklyn / Queens / Relocation",
  tagline: "Boutique New York real estate advisory for buyers, sellers, renters and investors.",
  heroImage: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=2200&q=82",
  strengths: ["24h shortlist", "NYC advisory", "AI-assisted matching"],
  inventory: [
    {
      market: "Tribeca, NYC",
      city: "New York",
      country: "US",
      title: "Tribeca Loft Residence",
      description: "High ceilings, full-service building, refined renovation, strong downtown liquidity.",
      addressDisplay: "Tribeca, Manhattan",
      assetClass: "Condo",
      priceDisplay: "$2.95M",
      areaSqm: "151",
      mediaUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=82",
      sellerSidePartner: "Aurum Key Realty NYC",
      buyerSidePartner: "Aurum Key Realty NYC",
    },
    {
      market: "Flatiron, NYC",
      city: "New York",
      country: "US",
      title: "Flatiron Designer Rental",
      description: "Doorman building, fast commute profile, premium finishes, immediate availability.",
      addressDisplay: "Flatiron District, Manhattan",
      assetClass: "Rental",
      priceDisplay: "$7,800/mo",
      mediaUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=82",
      sellerSidePartner: "Aurum Key Realty NYC",
      buyerSidePartner: "Aurum Key Realty NYC",
    },
    {
      market: "Brooklyn Heights, NYC",
      city: "New York",
      country: "US",
      title: "Brooklyn Heights Townhouse",
      description: "Historic character, private outdoor space, family-led layout, rare block quality.",
      addressDisplay: "Brooklyn Heights",
      assetClass: "Townhouse",
      priceDisplay: "$4.65M",
      mediaUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=82",
      sellerSidePartner: "Aurum Key Realty NYC",
      buyerSidePartner: "Aurum Key Realty NYC",
    },
  ],
};
