import type { PartnerTenantConfig } from "../types";

export const huajingTenant: PartnerTenantConfig = {
  key: "huajing",
  name: "华境置业",
  legalLabel: "HUAJING Estate Partners",
  city: "Shanghai",
  country: "China",
  domainLabel: "huajing.estate",
  accentLabel: "China / Dubai / Singapore / Tokyo",
  tagline: "Curated cross-border real estate advisory for private buyers and investors.",
  strengths: ["Curated inventory", "Broker review workflow", "Cross-border advisory"],
  inventory: [
    {
      market: "Shanghai, China",
      city: "Shanghai",
      country: "CN",
      title: "Riverside Cloud Residence",
      description: "Huangpu riverside apartment with private reception, skyline views and document review workflow.",
      addressDisplay: "Huangpu Riverside",
      assetClass: "apartment",
      priceDisplay: "From ¥18,600,000",
      areaSqm: "189",
      mediaUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=82",
      sellerSidePartner: "HUAJING Estate Partners",
      buyerSidePartner: "HUAJING Estate Partners",
    },
    {
      market: "Shenzhen, China",
      city: "Shenzhen",
      country: "CN",
      title: "Bay Area Prologue",
      description: "Qianhai Bay Area residence for technology founders and family relocation scenarios.",
      addressDisplay: "Qianhai Bay Area",
      assetClass: "apartment",
      priceDisplay: "From ¥12,800,000",
      areaSqm: "143",
      mediaUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=82",
      sellerSidePartner: "HUAJING Estate Partners",
      buyerSidePartner: "HUAJING Estate Partners",
    },
    {
      market: "Hangzhou, China",
      city: "Hangzhou",
      country: "CN",
      title: "Xixi Hidden Villa",
      description: "Low-density villa-style home near Xixi Wetland with private viewing and legal review required.",
      addressDisplay: "Xixi Wetland",
      assetClass: "house",
      priceDisplay: "From ¥9,600,000",
      areaSqm: "168",
      mediaUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=82",
      sellerSidePartner: "HUAJING Estate Partners",
      buyerSidePartner: "HUAJING Estate Partners",
    },
  ],
};
