steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - packages/db/Dockerfile.migrate
      - -t
      - europe-west4-docker.pkg.dev/$PROJECT_ID/kvartal/db-migrate:stage3a
      - .
images:
  - europe-west4-docker.pkg.dev/$PROJECT_ID/kvartal/db-migrate:stage3a
