steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/platform-api/Dockerfile
      - -t
      - europe-west4-docker.pkg.dev/$PROJECT_ID/kvartal/platform-api:stage3a
      - .
images:
  - europe-west4-docker.pkg.dev/$PROJECT_ID/kvartal/platform-api:stage3a
